title: VirtualBOSX Docs
description: An advanced guide for running early versions of Mac OS X on VirtualBox!
theme: just-the-docs
color_scheme: custom
favicon_ico: "/assets/logo.ico"
nav_sort: case_sensitive

url: https://pumpkintheproot.github.io/docs

callouts_opacity: 0.4
callouts:
  highlight:
    color: canary
  important:
    title: Important
    color: blueish
  new:
    title: New
    color: teal
  note:
    title: Note
    color: grey-lt
  warning:
    title: Warning
    color: reddish
  headsup:
    title: Heads Up!
    color: heads-up

# set up collections

# Define Jekyll collections
collections:
  writeups:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    writeups:
      name: WRITE UPS
      nav_exclude: false
      nav_fold: false
      search_exclude: false

# Set up includes
include:
 - docs
 - _sass
 - _layouts
 - _includes
# Aux links for the upper right navigation
aux_links:
  "View the Repo!":
    - "//github.com/pumpkintheproot/VirtualBOSX/tree/main"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
